theme: jekyll-theme-cayman
title: S³ seminar
description: The goal is to welcome recognized researchers, PhD students and post-docs on the field of signal processing, data science and its applications.
