# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
# paginate: 3 # jekyll-paginate > items per page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: s3_seminar # jekyll-seo-tag > Owners twitter username
author: "S3 seminar"
social: # jekyll-seo-tag > social overrides
  name: "S3 seminar"
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.youtube.com/channel/UC_S0ZvlJxOZ0ISNovvWKWdg
    - https://twitter.com/s3_seminar
    - https://www.l2s.centralesupelec.fr/seminaires/s3
    - https://s3-seminar.github.io

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  seminars:
    title: "S³ Seminars" # Needed for Siteleaf
    output: true
    description: "The S³ seminars" # The post list page content
    # feature_text: |
    #   The list of S³ seminars
    feature_image: "https://source.unsplash.com/1-aA2Fadydc"
    # feature_image: "https://picsum.photos/2560/600?image=733"
    # image: "https://picsum.photos/2560/600?image=733"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "seminars"
    values:
      layout: seminar # Set the default layout for posts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "S³ seminar"
logo: "/assets/logos/logo.png"
description: "The Paris-Saclay Signal Seminar"
url: "https://s3-seminar.github.io"
baseurl: ""
email: "seminaire.scube@l2s.centralesupelec.fr"

css_inline: true  # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Next Seminars
  url: /next_seminars/
- title: Past Seminars
  url: /past_seminars/
- title: Coming
  url: /coming/
- title: Search
  url: /search/

navigation_footer:
- title: "Author F. Orieux — Alembic theme"
  url: https://alembic.darn.es/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/s3_seminar
  SpeakerDeck: https://speakerdeck.com/s3_seminar
  link: https://s3-seminar.github.io
  youtube: https://www.youtube.com/channel/UC_S0ZvlJxOZ0ISNovvWKWdg

contact:
  Twitter: https://twitter.com/s3_seminar
  SpeakerDeck: https://speakerdeck.com/s3_seminar
  link: https://s3-seminar.github.io
  youtube: https://www.youtube.com/channel/UC_S0ZvlJxOZ0ISNovvWKWdg

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  Email: true
